In [1]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d

In [2]:
M = np.zeros((2,2))
M

array([[0., 0.],
       [0., 0.]])

In [3]:
M[0,0]=1.
M[0,1]=3.
M[1,0]=5.
M[1,1]=7.

In [4]:
M

array([[1., 3.],
       [5., 7.]])

In [5]:
M.T

array([[1., 5.],
       [3., 7.]])

In [15]:
def Transponse(M):
    
    T = M.copy()
   # print(id(T),id(M))
    
    for i in range(T.shape[0]):
        for j in range(T.shape[1]):
            T[j,i] = M[i,j]
            
    return T

In [16]:
T = Transponse(M)

In [17]:
T

array([[1., 5.],
       [3., 7.]])

In [18]:
# Graficacion 3d
A = 1
B = 3
omega = 2*np.pi/10
N = 50

In [20]:
t = np.linspace(0,10,N)
#t
r = np.zeros((N,3))

In [21]:
r

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0