In [1]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d

In [2]:
M = np.zeros((2,2))
M

array([[0., 0.],
       [0., 0.]])

In [3]:
M[0,0]=1.
M[0,1]=3.
M[1,0]=5.
M[1,1]=7.

In [4]:
M

array([[1., 3.],
       [5., 7.]])

In [5]:
M.T

array([[1., 5.],
       [3., 7.]])

In [15]:
def Transponse(M):
    
    T = M.copy()
   # print(id(T),id(M))
    
    for i in range(T.shape[0]):
        for j in range(T.shape[1]):
            T[j,i] = M[i,j]
            
    return T

In [16]:
T = Transponse(M)

In [17]:
T

array([[1., 5.],
       [3., 7.]])

In [18]:
# Graficacion 3d
A = 1
B = 3
omega = 2*np.pi/10
N = 50

In [20]:
t = np.linspace(0,10,N)
#t
r = np.zeros((N,3))

In [24]:
r[:,0] = A*np.cos(omega*t)
r[:,1] = A*np.sin(omega*t)
r[:,2] = B*t
r

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 9.91790014e-01,  1.27877162e-01,  6.12244898e-01],
       [ 9.67294863e-01,  2.53654584e-01,  1.22448980e+00],
       [ 9.26916757e-01,  3.75267005e-01,  1.83673469e+00],
       [ 8.71318704e-01,  4.90717552e-01,  2.44897959e+00],
       [ 8.01413622e-01,  5.98110530e-01,  3.06122449e+00],
       [ 7.18349350e-01,  6.95682551e-01,  3.67346939e+00],
       [ 6.23489802e-01,  7.81831482e-01,  4.28571429e+00],
       [ 5.18392568e-01,  8.55142763e-01,  4.89795918e+00],
       [ 4.04783343e-01,  9.14412623e-01,  5.51020408e+00],
       [ 2.84527587e-01,  9.58667853e-01,  6.12244898e+00],
       [ 1.59599895e-01,  9.87181783e-01,  6.73469388e+00],
       [ 3.20515776e-02,  9.99486216e-01,  7.34693878e+00],
       [-9.60230259e-02,  9.95379113e-01,  7.95918367e+00],
       [-2.22520934e-01,  9.74927912e-01,  8.57142857e+00],
       [-3.45365054e-01,  9.38468422e-01,  9.18367347e+00],
       [-4.62538290e-01,  8.86599306e-01