In [1]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d

In [2]:
M = np.zeros((2,2))
M

array([[0., 0.],
       [0., 0.]])

In [3]:
M[0,0]=1.
M[0,1]=3.
M[1,0]=5.
M[1,1]=7.

In [4]:
M

array([[1., 3.],
       [5., 7.]])

In [5]:
M.T

array([[1., 5.],
       [3., 7.]])